export const SAVE_TEXT = 'SAVE_TEXT';
export const SAVE_TYPES = 'GET_TYPES';
export const SAVE_CURRENT_PAGE = 'SAVE_CURRENT_PAGE';
export const LOGIN_SUCCEED = 'LOGIN_SUCCEED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const SIGN_OUT = 'SIGN_OUT';
export const REGISTER_SUCCEED = 'REGISTER_SUCCEED';
export const REGISTER_FAILED = 'REGISTER_FAILED';